apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hv11
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hv11
    app.kubernetes.io/part-of: tkrw-pr714-0075-0005-app
  name: devfile-sample-hv11
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hv11
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hv11
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0005-tenant/tkrw-pr714-0075-0005-app/devfile-sample-hv11@sha256:72aa6089b53957fd1e22c912e1b0f0db0c6273c523aaecf1d4be779f8d0aa963
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
